# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20170405_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_four',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_one',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_three',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_two',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='exam.Question'),
        ),
        migrations.AlterField(
            model_name='test',
            name='teacher',
            field=models.CharField(default=b'Vipin Sir', max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_title',
            field=models.CharField(default=b'GenericTest', max_length=100),
        ),
    ]
