# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20170413_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscore',
            name='attempted',
            field=models.BooleanField(default=False),
        ),
    ]
